### ISSUE TITLE
Should use different connections for Publish and Subscribe

### ISSUE THREAD

**Issue by davidwtf** [billcobbler/casbin-redis-watcher#1]
I think, it should use different connections for Publish and Subscribe.  It will meet this error, when call AddPolicy:
>Failure from Redis subscription: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context

**Comment by billcobbler** [comment]
You are correct @davidwtf! Thanks for pointing it out. Latest merge should correct that.
