### ISSUE TITLE
Infinite Loop on connection loss

### ISSUE THREAD

**Issue by PhilippSeitz** [billcobbler/casbin-redis-watcher#14]
This causes an infinite loop on connection loss

https://github.com/billcobbler/casbin-redis-watcher/blob/c05521d98fa2c9b903d1326b5b25b06ffe20f7ad/watcher.go#L95-L100

**Comment by PhilippSeitz** [comment]
a possible solution could be to also reconnect the watcher. But then `w.connect` gets called twice during start. Not sure how to check if it's connected or not

```go
	go func() {
		for {
			select {
			case <-w.closed:
				return
			default:
				err := w.connect(addr)
				if err == nil {
					err = w.subscribe()
				}
				if err != nil {
					fmt.Printf("Failure from Redis subscription: %v\n", err)
				}
				time.Sleep(2 * time.Second)
			}
		}
	}()
```

**Comment by hsluoyz** [comment]
@nodece @dovics please review.

**Comment by billcobbler** [comment]
Thanks for the report. We can add a `connected` check to the watcher that can check the underlying [redis.Conn's Err()](https://godoc.org/github.com/cespare/kvcache/internal/github.com/garyburd/redigo/redis#Conn), if that works as I expect (and returns an error if the connection hasn't been connected yet).

**Comment by billcobbler** [comment]
Went ahead and just embedded a check on each connection within watcher.connect. @PhilippSeitz can you review/test billcobbler/casbin-redis-watcher/17 and confirm that works for you?
