### ISSUE TITLE
How can I handle watcher when redis host is down or not available

### ISSUE THREAD

**Issue by cantv6605-seta** [billcobbler/casbin-redis-watcher#16]
@billcobbler @moranmathias @dallen42 @rwbarber2 @henrykin
I'm testing in case watcher connected to Redis host but for some reasons Redis host is down or not available or  ...
Currently, in this case, I see a lot of error messages like `Failure from Redis subscription: write tcp 192.168.80.133:44120->192.168.80.133:6379: use of closed network connection` 
It repeats forever, how can I handle this? It is blocking my program
![image](https://user-images.githubusercontent.com/33303166/90869621-ab943980-e3c2-11ea-90ed-10928d1badde.png)

Thanks!

**Comment by cantv6605-seta** [comment]
@billcobbler Could you take a look?

**Comment by hsluoyz** [comment]
@00LT00 can you also take a look at this issue?

**Comment by cantv6605-seta** [comment]
@all Can someone help to take a look at this? can we reconnect to redis host in this case?

**Comment by hsluoyz** [comment]
@cantv6605-seta forked here: https://github.com/casbin/redis-watcher as it seems there's already no response for 6 days..

**Comment by billcobbler** [comment]
Hey @cantv6605-seta, this looks like the behavior reported in #14. I just haven't had time to work on it.

**Comment by hsluoyz** [comment]
Hi @billcobbler , to better maintain this project, can we put this repo inside casbin org? Specifically: 

1. You can still maintain the project in: https://github.com/casbin/redis-watcher . Casbin team will also help you maintain it.
2. You will join Casbin as a member.

Let me know if it sounds OK for you. Thanks!

**Comment by billcobbler** [comment]
I'm happy to review any PRs y'all want to submit.

**Comment by cantv6605-seta** [comment]
> I'm happy to review any PRs y'all want to submit.

@billcobbler Can I have permission to create/submit a PR? I got 403 error when pushing a new branch.
Thanks!

**Comment by billcobbler** [comment]
@cantv6605-seta you just need to fork and submit a PR from your fork. But I also just pushed up #17 if you want to give that a shot and confirm it works for you.

**Comment by cantv6605-seta** [comment]
@billcobbler Could you help to release the latest version for go modules?

**Comment by billcobbler** [comment]
You bet, just released v1.0.1
