### ISSUE TITLE
Is there a mechanism to restore the redis connection?

### ISSUE THREAD

**Issue by onezero11010** [billcobbler/casbin-redis-watcher#21]
When the connection timed out and was disconnected by proxy of redis cluster, it was not found or restored.

Is there a plan to deal with this problem？

**Comment by billcobbler** [comment]
It should already attempt to reconnect every 2 seconds as driven by this loop [here](https://github.com/billcobbler/casbin-redis-watcher/blob/master/watcher.go#L90).

**Comment by asura-10** [comment]
I found this piece of code.
But I test it in my localhost, When I restart the instance of redis , it will be reconnected,  When I add iptables policy below

**Comment by onezero11010** [comment]
I found this piece of code.
But I test it in my localhost, When I restart the instance of redis , it will be reconnected, When I add iptables policy below

iptables -A OUTPUT -p tcp -m tcp --tcp-flags PSH PSH --sport 6379 -j DROP

My code showed nothing, doesn't show  retry connect information.

**Comment by onezero11010** [comment]
one more question,  why the reconnection code only exists in NewWatcher? not in NewPublishWatcher?

**Comment by hsluoyz** [comment]
@closetool

**Comment by hsluoyz** [comment]
@billcobbler

**Comment by uran0sH** [comment]
> I found this piece of code.
> But I test it in my localhost, When I restart the instance of redis , it will be reconnected, When I add iptables policy below
> 
> iptables -A OUTPUT -p tcp -m tcp --tcp-flags PSH PSH --sport 6379 -j DROP
> 
> My code showed nothing, doesn't show retry connect information.

It doesn't seem that it allows the packet to be sent out

**Comment by onezero11010** [comment]
> > I found this piece of code.
> > But I test it in my localhost, When I restart the instance of redis , it will be reconnected, When I add iptables policy below
> > iptables -A OUTPUT -p tcp -m tcp --tcp-flags PSH PSH --sport 6379 -j DROP
> > My code showed nothing, doesn't show retry connect information.
> 
> It doesn't seem that it allows the packet to be sent out

yes, I drop the network packages, it should be try reconnecting after a period of time, but it doesn't.

**Comment by hsluoyz** [comment]
@asura-10 can you debug the code and set a breakpoint inside: https://github.com/billcobbler/casbin-redis-watcher/blob/master/watcher.go#L90 , see whether it is get called?

**Comment by onezero11010** [comment]
> @asura-10 can you debug the code and set a breakpoint inside: https://github.com/billcobbler/casbin-redis-watcher/blob/master/watcher.go#L90 , see whether it is get called?

Maybe it need a long period of time , about 20 mins, so I close this issue now, thanks
